### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by alejandropg** [consoleau/kassava#7]
Hello @jamesbassett 

I would like to know if this project is still alive, because I would like to make some contributions.

My plan is:

1. Actualice versions of Kassava Benchmark, to get that the benchmark project uses the same than this project. Also this will allow to use benchmark with JVM 11 (PR already pending #https://github.com/consoleau/kassava-benchmarks/pull/1)
2. Add to Kassava Benchmark the tests for hashCode
3. Improve Kassava performance a little. I did some tests in local and the equals method has less improvement, but I think that the hashCode and toString methods could be interesting. So I would like that you review the changes and give me your opinion.

Thanks a lot!

**Comment by jamesbassett** [comment]
Yeah it's not dead, but I haven't really had much need to come back to it. Happy for you to raise a PR if you're keen and can make any improvement. Just keep the JDK8 compatibility (we're still on JDK8 Corretto at work for now).

**Comment by alejandropg** [comment]
Great!

I think that my local changes are all JDK8 compatible. Anyway, when I prepare the PR you can check and if not, tell me and I could change whatever you need.
